# Generated by Django 4.1.7 on 2023-07-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0002_alter_subscribe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
